@extends('layouts.business')
@section('title', 'Messaging API: Document')
@section('head') @include('layouts.partials.headersection',['title'=>'Developer\'s API Documentation']) @endsection
@section('end_head')
<style>
	.wa-content .alert code{background-color: unset;}

	.parameter-table{
		border-radius: 10px;
		overflow: hidden;
		margin-bottom: 0px;
		font-size: 12px;
	}
	/* .parameter-table td, 
	.parameter-table th{
		height: 45px!important;
	} */
	.parameter-table td:first-child{
		font-size: 13px;
		font-family: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
	}
	.card.bg-dark{
		background-color: #152f4a!important;
	}

	.copy-ico{
		cursor: pointer;
	}

	.lh-normal,
	.lh-normal p{
		/* line-height: 1.5; */
	}

	.code-area{
		color: #FFF!important;
		font-family: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
	}
</style>
@endsection
@section('content')
<section class="section">
    <div class="section-body">

		<div class="row">
			<div class="col-lg-3">
				<div class="sticky-top pb-3" style="top: 0rem;">
					<div class="card mb-0">
						<div class="card-body p-0">
							<div class="list-group" id="menu_cs_api_doc">
								<a href="#docs_sec_1" class="list-group-item list-group-item-action border-0 clickscroll">What is MouthPublicity Messaging API?</a>
								<a href="#docs_sec_3" class="list-group-item list-group-item-action border-0 clickscroll">Parameters</a>
								<a href="#docs_sec_4" class="list-group-item list-group-item-action border-0 clickscroll">GET Method</a>
								<a href="#docs_sec_5" class="list-group-item list-group-item-action border-0 clickscroll">POST Method</a>
								<a href="#docs_sec_6" class="list-group-item list-group-item-action border-0 clickscroll">Success Response</a>
								<a href="#docs_sec_7" class="list-group-item list-group-item-action border-0 clickscroll">Error Response</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-9">
		
				<div class="card" style="overflow: hidden;">
					<div class="card-body p-0">

						<div class="border-bottom" id="docs_sec_1">
							<div class="row">
								<div class="col-md-7">
									<div class="p-3 lh-normal pb-md-5 pb-4 pt-md-5">
										<p class="text-primary h6 mb-4"><b>What is MouthPublicity Messaging API?</b></p>
										<p class="mb-0">The MouthPublicity Messaging API allows you to integrate your billing software and send messages to your customer’s WhatsApp. You can send billing messages, notifications, alerts, offers, and any custom message to individual customers directly on their WhatsApp.</p>
									</div>
								</div>
								<div class="col-md-5">
									<div class="h-100 bg-dark p-3 pb-md-5 d-none d-md-block">
										<div class="code-area">

										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="border-bottom" id="docs_sec_2">
							<div class="row">
								<div class="col-md-7">
									<div class="p-3 lh-normal pt-5 pb-md-5 pb-4">
										<p class="text-primary h6 mb-4"><b>Introduction</b></p>
										<p class="mb-0">
											MouthPublicity Messaging API calls are sent to the <span class="h6"><code>/api/v1/WHATSAPP_MESSAGE_API/send</code></span> endpoint regardless of message text type, but the content of the JSON message body differs for text of message. See the following documentation for information regarding the type of messages you want to send
										</p>
									</div>
								</div>
								<div class="col-md-5">
									<div class="h-100 bg-dark p-3 pt-md-5 pb-md-5">
										<div class="code-area">
											<p class="mb-0"><code class="text-info">Endpoint</code></p>
											<p class="mb-0">/api/v1/WHATSAPP_MESSAGE_API/send</p>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="border-bottom" id="docs_sec_3">
							<div class="row">
								<div class="col-md-7">
									<div class="p-3 lh-normal pb-md-5 pb-4 pt-5">
										<p class="text-primary h6 mb-4"><b>Parameters</b></p>
										<p class="mb-2">Every API request supports the following parameters.</p>
										<div class="table-responsive">
											<table class="table table-bordered table-striped parameter-table table-sm mb-0">
												<tr>
													<th>Parameter</th>
													<th>Type</th>
													<th>Info</th>
												</tr>
												<tr>
													<td>username</td>
													<td>string</td>
													<td>Autogenerated by the system after successfully QR code scan.</td>
												</tr>
												<tr>
													<td>password</td>
													<td>string</td>
													<td>Autogenerated by the system after successfully QR code scan.</td>
												</tr>
												<tr>
													<td>mobile</td>
													<td>12 Digits Number</td>
													<td>Include 91 before 10 digit WA mobile number where you want to send message</td>
												</tr>
												<tr>
													<td>sendername</td>
													<td>6 Digit Alphabet</td>
													<td>Autogenerated by the system after successfully QR code scan.</td>
												</tr>
												<tr>
													<td>message</td>
													<td>string</td>
													<td>text</td>
												</tr>
												<tr>
													<td>routetype</td>
													<td>boolean</td>
													<td>"0" or "1"</td>
												</tr>
											</table>
										</div>
									</div>
								</div>
								<div class="col-md-5">
									<div class="h-100 bg-dark p-3 pb-md-5 pt-md-5 d-none d-md-block">
										<div class="code-area">

										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="border-bottom" id="docs_sec_4">
							<div class="row">
								<div class="col-md-7">
									<div class="p-3 lh-normal pt-5 pb-md-5 pb-4">
										<p class="text-primary h6 mb-4"><b>API integration using <span class="text-danger">GET</span> Method</b></p>
										<p class="mb-1">Here is the example of MouthPublicity Messaging API from the <b class="text-danger">GET Method</b>.</p>
										<p class="mb-0">URL addresses that you need to use to connect to MouthPublicity WA API is:</p>
										<p><code>{{url('api/v1/WHATSAPP_MESSAGE_API/send?')}}</code></p>
										<p class="mb-0">Just copy & paste this URL in your POS system/Billing system.</p>
									</div>
								</div>
								<div class="col-md-5">
									<div class="h-100 bg-dark p-3 pt-md-5 pb-md-5">
										<div class="code-area">
											<code class="text-success">GET/</code>
											<p class="mb-0">{{ $api_url }}</p>
										</div>
									</div>
								</div>
							</div>
						</div>
		
						<div class="border-bottom" id="docs_sec_5">
							<div class="row">
								<div class="col-md-7">
									<div class="p-3 lh-normal pt-5 pb-md-5 pb-4">
										<p class="text-primary h6 mb-4"><b>API integration using <span class="text-danger">POST</span> Method</b></p>
										<p class="mb-0">Here is the example of MouthPublicity Messaging API from the <b class="text-danger">POST Method</b>.</p>
										<p class="mb-0">URL addresses that you need to use to connect to MouthPublicity WA API is:</p>
										<p class="mb-0"><code>{{url('api/v1/WHATSAPP_MESSAGE_API/send')}}</code></p>
									</div>
								</div>
								<div class="col-md-5">
									<div class="h-100 bg-dark p-3 pt-md-5 pb-md-5">
										<div class="code-area">
											<code class="text-success">POST/</code>
											<p><code>URL:</code> {{url('api/v1/WHATSAPP_MESSAGE_API/send')}}</p>
											<p class="mb-0"><code>Paremeters:</code></p>
											<table class="w-100 para-table mb-0">
												<tr>
													<td style="width: 75px">username</td>
													<td>:</td>
													<td>WAPIXXX</td>
												</tr>
												<tr>
													<td>password</td>
													<td>:</td>
													<td>********</td>
												</tr>
												<tr>
													<td>mobile</td>
													<td>:</td>
													<td>91XXXXXXXXXX</td>
												</tr>
												<tr>
													<td>sendername</td>
													<td>:</td>
													<td>BUSINESSXXX</td>
												</tr>
												<tr>
													<td>message</td>
													<td>:</td>
													<td>{{ $message }}</td>
												</tr>
												<tr>
													<td>routetype</td>
													<td>:</td>
													<td>1</td>
												</tr>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="border-bottom" id="docs_sec_6">
							<div class="row">
								<div class="col-md-7">
									<div class="p-3 lh-normal pt-5 pb-md-5 pb-4">
										<p class="text-primary h6 mb-4"><b>API Success Response</b></p>
										<p class="mb-0">Here is the example of the success response of the MouthPublicity Messaging API. All the responce are return in the <code>JSON</code> format.</p>
									</div>
								</div>
								<div class="col-md-5">
									<div class="h-100 bg-dark p-3 pt-md-5 pb-md-5">
										<div class="code-area">
											<code class="text-warning mb-2 d-block">JSON</code>
											<div>
												<pre class="text-white cp_responce" id="cp_responce1">{"status": true,"data": {"status":"success","message":"Success","data":{"key":{"remoteJid":"91XXXXXXXXXX@c.us","fromMe":true,"id":"BAE57F30D7A415FE"},"message":{"extendedTextMessage":{"text":"Test"}},"messageTimestamp":"1651315121","status":"PENDING"}},"message": "Sent Successfully!."}</pre>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="border-bottom" id="docs_sec_7">
							<div class="row">
								<div class="col-md-7">
									<div class="p-3 lh-normal pt-5 pb-md-5 pb-4">
										<p class="text-primary h6 mb-4"><b>API Error Responses</b></p>
										<p class="mb-1">Here is the example of the error response of the MouthPublicity Messaging API. All the responce are return in the <code>JSON</code> format.</p>
										<p class="mb-0">Below is the list of error messages:</p>
										<ul class="mb-0">
											<li>Sendername is invalid.</li>
											<li>Whatsapp number is invalid.</li>
											<li>Messaging Api data not found.</li>
										</ul>

									</div>
								</div>
								<div class="col-md-5">
									<div class="h-100 bg-dark p-3 pt-md-5 pb-md-5">
										<div class="code-area">
											<code class="text-warning mb-2 d-block">JSON</code>
											<div>
												<pre class="text-white cp_responce" id="cp_responce2">{"status": false,"data": [],"message": "Sendername is invalid."}</pre>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
		
					</div>
				</div>
			</div>
		</div>


	</div>
</section>
@endsection
@section('end_body')
    {{-- @include('business.scripts.whatsapp-js')
    @include('business.scripts.profile-setting') --}}


	<script>
	
	    (function() {
			$(".cp_responce").each(function(){
				var obj = JSON.parse($(this).html());
				$(this).html(JSON.stringify(obj, undefined, 2))
			});
		})();


		// Cache selectors
		var lastId,
			topMenu = $("#menu_cs_api_doc"),
			topMenuHeight = topMenu.outerHeight()+15,
			// All list items
			menuItems = topMenu.find("a"),
			// Anchors corresponding to menu items
			scrollItems = menuItems.map(function(){
			var item = $($(this).attr("href"));
				if (item.length) { return item; }
			});

		// Bind click handler to menu items
		// so we can get a fancy scroll animation
		menuItems.click(function(e){
			var href = $(this).attr("href"),
				offsetTop = href === "#" ? 0 : $(href).offset().top;
			$('html, body').stop().animate({ 
				scrollTop: offsetTop
			}, 300);
			e.preventDefault();
		});

		// Bind to scroll
		$(window).scroll(function(){
			// Get container scroll position
			var fromTop = $(this).scrollTop() + topMenuHeight;
			
			// Get id of current scroll item
			var cur = scrollItems.map(function(){
				if ($(this).offset().top < fromTop)
				return this;
			});
			// Get the id of the current element
			cur = cur[cur.length-1];
			var id = cur && cur.length ? cur[0].id : "";
			
			if (lastId !== id) {
				lastId = id;
				// Set/remove active class
				menuItems
					.removeClass("active")
					.end().filter("[href='#"+id+"']").addClass("active");
			}
		});

	</script>

	<script>
		function credential(){
			
			var username = "{{ ($apiData != null ) ? $apiData->username : '' }}";
			var password = "{{ ($apiData != null ) ? $apiData->password : '' }}";
			var sendername = "{{ ($apiData != null ) ? $apiData->sendername : '' }}";

			Swal.fire({
				title: '<h5>Credentials</h5>',
				text: 'You clicked the button!',
				icon: 'info',
				allowOutsideClick: false,
				showConfirmButton: false,
				showCloseButton: true,
				html:'<table class="table text-left table-sm mx-auto" style="max-width:320px;">' +
					'<tr>' +
						'<td style="color:var(--primary);font-weight:500;">Username</td>' +
						'<td>:</td>' +
						'<td><font face="monospace" id="un_copy">'+username+'</font></td>' +
						'<td><i class="far fa-copy copy-ico" data-toggle="tooltip" title="Copy" onclick="copyToClipboard(\'#un_copy\');$(this).attr(\'title\',\'Copied!\');"></i></td>' +
					'</tr>' +
					'<tr>' +
						'<td style="color:var(--primary);font-weight:500;">Password</td>' +
						'<td>:</td>' +
						'<td><font face="monospace" id="pw_copy">'+password+'</font></td>' +
						'<td><i class="far fa-copy copy-ico" data-toggle="tooltip" title="Copy" onclick="copyToClipboard(\'#pw_copy\');$(this).attr(\'title\',\'Copied!\');"></i></td>' +
					'</tr>' +
					'<tr>' +
						'<td style="color:var(--primary);font-weight:500;">Sender Name</td>' +
						'<td>:</td>' +
						'<td><font face="monospace" id="sn_copy">' +sendername+ '</font></td>' +
						'<td><i class="far fa-copy copy-ico" data-toggle="tooltip" title="Copy" onclick="copyToClipboard(\'#sn_copy\');$(this).attr(\'title\',\'Copied!\');"></i></td>' +
					'</tr>' +
					'</table>',
			})
		}
	</script>
@endsection